df <- read.csv("household_power_consumption.txt", sep=';', na.strings="?")
df <- df[df$Date == "1/2/2007" | df$Date == "2/2/2007",]
df$datetime = strptime(paste(df$Date, df$Time), "%d/%m/%Y %H:%M:%S")
png("plot3.png")
Sys.setlocale("LC_TIME", "English")
with(df, plot(datetime, Sub_metering_1, type="l", xlab="", ylab="Energy sub metering"))
with(df, lines(datetime, Sub_metering_2, type="l", col="red"))
with(df, lines(datetime, Sub_metering_3, type="l", col="blue"))
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lwd=1)
Sys.setlocale("LC_TIME", "")
dev.off()
